### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by Icikowski** [Luzifer/ots#142]
> **As** a system administrator
> **I want** to have access to metrics regarding number of stored secrets, number of secret creation errors, number of secret read errors, attachment sizes and so on
> **So** I can monitor the status of the `OTS` application, create statistics and prepare alert rules

Metrics would provide a nice insight into the `OTS` status, as well as an opportunity to detect problems & take necessary actions as soon as possible.

The implementation would be prety painless due to the usage of interfaces. The way of incorporating metrics has been described in [Prometheus documentation](https://prometheus.io/docs/guides/go-application/). However, decision regarding the details of exposing `/metrics` endpoint has to be considered carefully - it should not be publicly available, so probably the best way would involve running dedicated server on separate port, listening only on `localhost`/`127.0.0.1` address.

Previously this idea was rejected (https://github.com/Luzifer/ots/issues/15), but this time I have another solution - instead of using external library, the application may use simplified internal code to serve this purpose. I'd be interested to help in implementation if the idea will catch on.

**Comment by Luzifer** [comment]
Indeed thought about this myself lately but haven't planned this yet.

> However, decision regarding the details of exposing `/metrics` endpoint has to be considered carefully - it should not be publicly available, so probably the best way would involve running dedicated server on separate port, listening only on `localhost`/`127.0.0.1` address.

I'd argue securing the endpoints is not part of OTS itself but this can more easily be solved by limiting endpoint access instead of another server. Also limiting to `localhost` doesn't make sense as - judging from my standpoint as a K8s cluster admin - the access to the metrics endpoint never will be from localhost. So this should be configurable (and speaking in terms of a K8s cluster need to be secured in the Ingress as IP limitation wouldn't limit anything).

Which metrics do you see useful?

| Metric | Type | Desc |
| ---- | ---- | ---- |
| `ots_secrets_created` | `counter` | Increased as soon as a secret is stored into the backend storage |
| `ots_secrets_read` | `counter` | Increased as soon as a secret is read and deleted from the backend storage |
| `ots_secrets_create_errors{reason="..."}` | `counter` | Increased as a counter-vector differentiated by rejection reason |
| `ots_secrets_read_errors` | `counter` | Increased on secrets not found while accessing (allows for alerting on brute-force access) |

Attachment sizes cannot be tracked. The server will never know details about the contents of the secret.

**Comment by Icikowski** [comment]
> I'd argue securing the endpoints is not part of OTS itself but this can more easily be solved by limiting endpoint access instead of another server. Also limiting to `localhost` doesn't make sense as - judging from my standpoint as a K8s cluster admin - the access to the metrics endpoint never will be from localhost. So this should be configurable (and speaking in terms of a K8s cluster need to be secured in the Ingress as IP limitation wouldn't limit anything).

You're absolutely right, I forgot about cases any other than bare metal deployment, though I'm using your solution in K8s as well, I apologize.

As for the metrics, I'm convinced that all of them are useful - to be honest, when opening this issue I had those four in mind, as well as `gauge` one representing the number of currently stored secrets (let's name it `ots_secret_count`), which can be handy to determine the current load of an instance.

**Comment by Luzifer** [comment]
Added the count as `ots_secrets_stored`… …will do some refactoring when implementing that but should be possible with all backends in a performant manner.
