### ISSUE TITLE
Improve UX for secrets with attachments

### ISSUE THREAD

**Issue by sorcix** [Luzifer/ots#149]
When viewing a secret with both text and an attachment, people don't always notice the attachment links. Especially when there's only a single attachment with a short name. Due to how OTS works, when they copy the secret and navigate away, the attachment is gone. This makes it very important that they notice the links at the bottom.

Can we make attachments stand out more?

**Comment by Luzifer** [comment]
Hmmm yeah, I see the point… 🤔 

Do you have any suggestions how to make them stand out more?

I could imagine something like a file explorer view with tiles… …has the disadvantage I'd need to possibly shorten the filenames which isn't wise as somebody could use that to hide file extensions…

I also could imagine a list view having a ["file icon" ](https://fontawesome.com/search?q=file-&o=r&m=free&s=solid) in front, the name, the size and a yellow warning-triangle at the end which disappears after downloading the file (clicking the entry)… …should draw attention to the list…

Maybe a warning alert "Remember to download your files" which vanishes after all files have been clicked once? That might be overkill…

From those three variants I do like the second (list view) most…

**Comment by sorcix** [comment]
I was experimenting with something like this. Not sure if it's any better, though..

![image](https://github.com/Luzifer/ots/assets/65006/1ae71eac-4a2b-4780-b49c-b0b3dd7d6eef)

**Comment by Luzifer** [comment]
Had basically the same idea with the list-view suggestion:

In both cases the `test.txt` has been downloaded so the warning triangle switches to the check-mark as soon as the file was downloaded… Otherwise used the icon as some "eye-candy" to get the users attention to that file…

Not sure though whether I should use the warning triangle or just color the icon… …the triangle might send a false signal something is wrong with that file… 🤔 

![image](https://github.com/Luzifer/ots/assets/20142/99348174-b3c7-4fb2-9452-b88047f9860f)
![image](https://github.com/Luzifer/ots/assets/20142/ed462d9d-c692-4183-bc5a-c7d7456c441f)

**Comment by sorcix** [comment]
Ah, yours looks a lot better. The yellow warning triangle combined with the message above the list may scare people into thinking the file is malware though. Maybe use the standard "download" font awesome icon instead? (But keep the check when it's downloaded, that's great!)

**Comment by Luzifer** [comment]
![image](https://github.com/Luzifer/ots/assets/20142/ab689901-b52d-4fdd-9f3f-efe0664a6873)
