### ISSUE TITLE
Feature request: possibility to revoke/burn a secret

### ISSUE THREAD

**Issue by mshedsilegx** [Luzifer/ots#170]
I would be helpful to be able to burn or revoke a secret immediately in case of error or mistake, to invalidate it right away.
Similar to the below.
![image](https://github.com/Luzifer/ots/assets/32753787/a33b2c35-df1a-4cd4-9df6-9653a067b6c4)

If the secret is passphrase protected, the correct passphrase would need to be entered to revoke/burn the secret.

**Comment by Luzifer** [comment]
Well, just call the URL you got and retrieve it, it's immediately deleted from the server and therefore gone.

**Comment by mshedsilegx** [comment]
I agree, still I think it would more user friendly to be able to revoke a secret via a UI button, without having to view it.

**Comment by mshedsilegx** [comment]
Closing, as this feature is only a nice to have,

**Comment by Luzifer** [comment]
> Closing, as this feature is only a nice to have,

Then why are you closing it, if you want to have it?

**Comment by HappyMan4** [comment]
Hi Luzifer, I've had a few moments when I needed that button.
Let's say you pasted a wrong text into the form and created the secret. Afterwards you realize that you just pasted the wrong text into it.
So the next decision is up to the user - mostly I don't take the time to copy the link and call it so that the server forgets the information. I just leave it as it is, with the default expiry time to expire by itself. On my site this is seven days.
If there would be a button to destroy the information immediately, at least for me, I could see a benefit here.
But indeed, this is just nice to have and nothing more. It's really not important at all.
Just my 2 cents 😊

**Comment by mshedsilegx** [comment]
I agree, that was my sentiment originally as well, just did not want to waste valuable development time on a trivial feature.

**Comment by Luzifer** [comment]
@mshedsilegx @HappyMan4 Please have a look at the attached PR (including screenshots) for the implementation draft of this feature.

**Comment by mshedsilegx** [comment]
That looks excellent, thank you for doing this.
