### ISSUE TITLE
Create "How to  Whitelabel" Wiki page

### ISSUE THREAD

**Issue by Luzifer** [Luzifer/ots#94]
> As an OPS engineer I don't want to guess how to set-up and secure the instance so nobody outside the company can create secrets on it.

Therefore a little "Walk-Through" would be great to have. It should

- [x] demonstrate setting up a plain OTS (plain Docker)
- [x] show how to customize the instance
- [x] get into detail how to secure the instance using nginx proxy module

**Comment by cymric73** [comment]
This would be very helpful. This app would be very useful for my Service Desk but I'm struggling to customize it to my liking. A few wiki questions for consideration. I'm able to download the linux binary, run it no problem and make use of the yaml customization file, all good there. 

My current struggles are when I venture to explore what I can make and modify from source: (disclaimer: I have experience as a Linux Admin and Developer, but Go is new to me, so apologies in advance if these would be obvious to an experienced Go developer which I am not ;-):
1)  I can build ots from source, and have previously run "make fontawesome" to fill the "frontend" directory, but when I visit the page I get this error:
"error calling assetSRI: opening file: open webfonts/fa-solid-900.woff2: file does not exist", yet the file is present in the frontend directory.
2) How do I configure it to use redis for persistence between reboots?

**Comment by cymric73** [comment]
I was able to get past the error "calling assetSRI: opening file: open webfonts/fa-solid-900.woff2: file does not exist" by using the command: > go run . instead of ./ots. (Not sure why but moving on....) 

Next got the same error but asking for the latofont files. I had to copy them from under src/ to the frontend/ directory to allow them to be found by the web server. 

Now I'm getting the error: "error calling assetSRI: opening file: open app.css: file does not exist". I don't see this file anywhere in the 1.7.0 source so now I'm stuck....any insight would be appreciated. 

Is there a build package step I'm missing, I didn't see any such task in the Makefile?

**Comment by Luzifer** [comment]
You were missing `make generate`: I've added a `build-local` target to the Makefile and put the documentation [here](https://github.com/Luzifer/ots/wiki#building-from-source).

For further questions please open a new issue and don't hijack an issue not related to building from source for build-related questions.

**Comment by Luzifer** [comment]
Page created as main page of the Wiki: https://github.com/Luzifer/ots/wiki
